import Ember from 'ember';

export default Ember.Controller.extend({
	needs: ['index','patient'],
	operatingSurgeon: ['Evans',
					   'Farrell',
					   'Judy',
					   'Andrews',
					   'Rosen',
					   'Nyquist'],
	tumorLocation: ['Anterior Fossa',
					'Cavernous Sinus',
					'Clivus',
					'Ethmoid',
					'Middle Fossa',
					'Pituitary - Sellar',
					'Pituitary - Suprasellar',
					'Posterior Fossa',
					'Petrous Apex',
					'Orbit',
					'Sphenoid Sinus',
					'Cervical Spine'],
	resection: ['Total',
				'Subtotal',
				'Partial',
				'Biopsy',
				'None'],
	repairMaterial: ['Surgicel',
					 'Durepair',
					 'Duraseal Glue',
					 'Duragen',
					 'Gelfoam',
					 'Gelfilm',
					 'Floseal',
					 'Surgifoam',
					 'Tisseal',
					 'Button',
					 'Gasket',
					 'Medpore',
					 'Nasoseptal Flap',
					 'U Clip',
					 'Cartilage',
					 'Fascia Lata',
					 'Nasal Packing',
					 'Fat Graft'],
	approach: ['Transsphenoidal',
			   'Transorbital',
			   'Frontotemporal',
			   'Infratemporal',
			   'Transoral',
			   'Transmaxillary',
			   'Transplanum',
			   'Transtuberculum',
			   'Caldwell-Luc',
			   'Transethmoidal',
			   'Craniofacial',
			   'Retrosigmoid'],
	complications: ['Hematoma',
					'Diabetes Insipidus',
					'Myocardial Infarction',
					'Lumbar Drain',
					'Sinusitis',
					'SIADH',
					'CSF Leak',
					'DVT',
					'Stroke',
					'Carotid Artery Rupture',
					'Epistaxis',
					'Sphenoiditis']

});
